cut_point:
  prev:
    - 0.1
    - 0.4
    - 0.5
    - 1.0
  next:
    - 0.1
    - 0.4
    - 0.0
    - 0.5
  self:
    - 0.333
    - 0.5
    - 0.0
    - 1.0
  landlord:
    - 0.0
threshold: 0
name: light
